title:            Eric Helgeson
description:      A blog by Eric.
url:              http://erichelgeson.github.io
signoff:          -Eric
disqus_shortname: erichelgesonblog # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-37860645-1 # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /
  - name:         Email
    url:          mailto:erichelgeson+blog@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/erichelgeson
    external:     true
  - name:         RSS
    url:          http://feeds.feedburner.com/EricHelgesonBlog
    external:     true
#pygments:         true
highlighter:      rouge
permalink:        pretty
markdown:         redcarpet
#redcarpet:
#  extensions:
#    - smart
#    - tables
